# Generated by Django 4.0.4 on 2022-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='client/')),
            ],
        ),
    ]
